version: "3.9"
services:
  postgres:
    image: postgres:14-bullseye
    environment:
      POSTGRES_DB: walletengine
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
  # engine:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"