apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  selector:
    app: engine
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine-api
          image: fadelpm/engine-multi:latest
