name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: "Create env file"
        run: |
          touch env.yaml
          cat << EOT >> env.yaml
          port: ${{ secrets.PORT }}
          database:
            mongo_timeout: ${{ secrets.MONGO_TIMEOUT }}
            mongo_db_name: ${{ secrets.MONGO_DB_NAME }}
            mongo_uri: ${{ secrets.MONGO_URI }}
          EOT
          cat env.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Inspect Buildx builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Driver:    ${{ steps.buildx.outputs.driver }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fadelpm/engine-multi:latest
